/// iot-flow code generator
///
/// Generates zero‑runtime Rust or embedded C source from an AST.
///
/// Author: Myroslav Mokhammad Abdeljawwad

use std::fmt;
use std::io::{self, Write};

use crate::parser::ast::{
    AstNode,
    Expression,
    Statement,
    VariableType,
};
use thiserror::Error;

/// Target language for code generation.
#[derive(Debug, Clone, Copy)]
pub enum Language {
    Rust,
    C,
}

impl fmt::Display for Language {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Language::Rust => write!(f, "rust"),
            Language::C => write!(f, "c"),
        }
    }
}

/// Errors that can occur during code generation.
#[derive(Debug, Error)]
pub enum CodegenError {
    #[error("I/O error while writing output: {0}")]
    Io(#[from] io::Error),

    #[error("Unsupported expression type in generator")]
    UnsupportedExpression,

    #[error("Unsupported statement type in generator")]
    UnsupportedStatement,
}

/// The main code generator struct.
pub struct Generator {
    /// Target language for generation.
    lang: Language,
}

impl Generator {
    /// Create a new generator targeting the given language.
    pub fn new(lang: Language) -> Self {
        Self { lang }
    }

    /// Generate source code from an AST.
    ///
    /// The generated code is returned as a `String`. Errors are wrapped in
    /// [`CodegenError`].
    pub fn generate(&self, ast: &AstNode) -> Result<String, CodegenError> {
        let mut output = Vec::new();
        self.write_header(&mut output)?;
        self.visit_node(ast, 0, &mut output)?;
        self.write_footer(&mut output)?;

        String::from_utf8(output).map_err(|e| {
            io::Error::new(io::ErrorKind::InvalidData, e)
                .into()
        })
    }

    fn write_header<W: Write>(&self, out: &mut W) -> Result<(), CodegenError> {
        match self.lang {
            Language::Rust => writeln!(
                out,
                "// Generated by iot-flow v0.1.0\n\
                 // Author: Myroslav Mokhammad Abdeljawwad\n\
                 \n\
                 use std::sync::mpsc::{self, Sender, Receiver};\n\
                 use std::thread;\n"
            )?,
            Language::C => writeln!(
                out,
                "// Generated by iot-flow v0.1.0\n\
                 // Author: Myroslav Mokhammad Abdeljawwad\n\
                 \n\
                 #include <stdio.h>\n\
                 #include <stdlib.h>\n"
            )?,
        }
        Ok(())
    }

    fn write_footer<W: Write>(&self, out: &mut W) -> Result<(), CodegenError> {
        match self.lang {
            Language::Rust => writeln!(out, "\nfn main() {{\n    println!(\"Execution complete.\");\n}}")?,
            Language::C => writeln!(
                out,
                "\nint main(void) {{\n    printf(\"Execution complete.\\n\");\n    return 0;\n}}"
            )?,
        }
        Ok(())
    }

    fn visit_node<W: Write>(
        &self,
        node: &AstNode,
        indent: usize,
        out: &mut W,
    ) -> Result<(), CodegenError> {
        match node {
            AstNode::Statement(stmt) => self.visit_statement(stmt, indent, out),
            AstNode::Expression(expr) => self.visit_expression(expr, indent, out),
        }
    }

    fn visit_statement<W: Write>(
        &self,
        stmt: &Statement,
        indent: usize,
        out: &mut W,
    ) -> Result<(), CodegenError> {
        match stmt {
            Statement::Let { name, var_type, expr } => {
                let type_str = self.type_to_string(var_type);
                writeln!(
                    out,
                    "{}let {}: {} = {};",
                    " ".repeat(indent),
                    name,
                    type_str,
                    self.expr_to_code(expr)?
                )?;
            }
            Statement::Assign { target, expr } => {
                writeln!(
                    out,
                    "{}{} = {};",
                    " ".repeat(indent),
                    target,
                    self.expr_to_code(expr)?
                )?;
            }
            Statement::If { cond, then_branch, else_branch } => {
                writeln!(out, "{}if {} {{", " ".repeat(indent), self.expr_to_code(cond)?)?;
                for n in then_branch {
                    self.visit_node(n, indent + 4, out)?;
                }
                if let Some(else_nodes) = else_branch {
                    writeln!(out, "{}}} else {{", " ".repeat(indent))?;
                    for n in else_nodes {
                        self.visit_node(n, indent + 4, out)?;
                    }
                }
                writeln!(out, "{}}}", " ".repeat(indent))?;
            }
            Statement::While { cond, body } => {
                writeln!(
                    out,
                    "{}while {} {{",
                    " ".repeat(indent),
                    self.expr_to_code(cond)?
                )?;
                for n in body {
                    self.visit_node(n, indent + 4, out)?;
                }
                writeln!(out, "{}}}", " ".repeat(indent))?;
            }
            Statement::Block(nodes) => {
                writeln!(out, "{}{{", " ".repeat(indent))?;
                for n in nodes {
                    self.visit_node(n, indent + 4, out)?;
                }
                writeln!(out, "{}}}", " ".repeat(indent))?;
            }
        }
        Ok(())
    }

    fn visit_expression<W: Write>(
        &self,
        expr: &Expression,
        _indent: usize,
        _out: &mut W,
    ) -> Result<(), CodegenError> {
        // Expressions are inlined via `expr_to_code`; nothing to do here.
        Ok(())
    }

    fn expr_to_code(&self, expr: &Expression) -> Result<String, CodegenError> {
        match expr {
            Expression::LiteralInt(i) => Ok(i.to_string()),
            Expression::LiteralFloat(f) => Ok(format!("{:.6}", f)),
            Expression::LiteralBool(b) => Ok(b.to_string()),
            Expression::Variable(name) => Ok(name.clone()),
            Expression::Binary { left, op, right } => {
                let l = self.expr_to_code(left)?;
                let r = self.expr_to_code(right)?;
                Ok(format!("({} {} {})", l, op.as_str(), r))
            }
            Expression::Unary { op, expr: inner } => {
                let e = self.expr_to_code(inner)?;
                Ok(format!("{}{}", op.as_str(), e))
            }
        }
    }

    fn type_to_string(&self, var_type: &VariableType) -> &'static str {
        match var_type {
            VariableType::Int => "i32",
            VariableType::Float => "f64",
            VariableType::Bool => "bool",
            VariableType::String => "&'static str",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::ast::{
        AstNode,
        Expression,
        Statement,
        VariableType,
    };

    fn sample_ast() -> AstNode {
        AstNode::Statement(Statement::Block(vec![
            AstNode::Statement(Statement::Let {
                name: "x".into(),
                var_type: VariableType::Int,
                expr: Box::new(Expression::LiteralInt(42)),
            }),
            AstNode::Statement(Statement::If {
                cond: Box::new(Expression::Binary {
                    left: Box::new(Expression::Variable("x".into())),
                    op: ExpressionOperator::Gt,
                    right: Box::new(Expression::LiteralInt(10)),
                }),
                then_branch: vec![AstNode::Statement(Statement::Assign {
                    target: "x".into(),
                    expr: Box::new(Expression::Binary {
                        left: Box::new(Expression::Variable("x".into())),
                        op: ExpressionOperator::Plus,
                        right: Box::new(Expression::LiteralInt(1)),
                    }),
                })],
                else_branch: None,
            }),
        ]))
    }

    #[test]
    fn test_generate_rust() {
        let gen = Generator::new(Language::Rust);
        let code = gen.generate(&sample_ast()).expect("generation failed");
        assert!(code.contains("let x: i32 = 42;"));
        assert!(code.contains("if (x > 10) {"));
    }

    #[test]
    fn test_generate_c() {
        let gen = Generator::new(Language::C);
        let code = gen.generate(&sample_ast()).expect("generation failed");
        assert!(code.contains("#include <stdio.h>"));
        // C output is currently still Rust style; placeholder for future.
    }
}